# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - working-directory: './computation'
      name: Install (Computation)
      run: npm install

    - working-directory: './computation'
      name: Lint (Computation)
      run: npm run lint

    - working-directory: './graphics/starfield'
      name: Install (Starfield)
      run: npm install

    - working-directory: './graphics/starfield'
      name: Lint (Starfield)
      run: npm run lint

    - working-directory: './graphics/fire'
      name: Install (Fire Effect)
      run: npm install

    - working-directory: './graphics/fire'
      name: Lint (Fire Effect)
      run: npm run lint
